### ISSUE TITLE
zui16.0.617 cannot edit file in TWRP

### ISSUE THREAD

**Issue by kazegh** [polygraphene/android_device_lenovo_TB320FC#3] opened 2024-11-27 07:13 UTC
Y700 2023 TB320FC- zui16.0.617 cannot boot in LENOVO logo and cannot reboot to recovery mode.

**Comment by polygraphene** [comment] 2024-11-27 09:13
Thank you for reporting.
Was it working on older CN rom?

One possible cause of the issue is that kernel incompatibility.
Currently, kernel modules are [embedded on the recovery](https://github.com/polygraphene/android_device_lenovo_TB320FC/tree/06a0df54c4245dffc1ecec1d0433ea244e4fd08d/recovery/root/lib/modules). Those modules might be unable to be loaded on newer kernel.

I will test it later.

**Comment by kazegh** [comment] 2024-11-29 09:22
Sorry.I didnot test it for older CN rom. Because I want to keep my tablet's data. I will wait for your fixed TWRP or find other way to solve with it.

**Comment by kazegh** [comment] 2024-11-29 09:23
Sorry.I didnot test it for older CN rom. Because I want to keep my tablet's data. I will wait for your fixed TWRP or find other way to solve with it.

**Comment by polygraphene** [comment] 2024-11-30 09:41
I tried CN 16.0.336. It works.
But I found I can't get ota to 617. It seems not yet available publicly.
Can you provide the link for ota fille?

**Comment by polygraphene** [comment] 2024-11-30 10:20
Did you try to re-flashed boot? In my environment, sometimes boot partition was broken after flashing recovery and booted into fastboot.

**Comment by kazegh** [comment] 2024-11-30 11:18
Thank you very much. I re-flashed the boot. It worked. The tablet booted in the TWRP.(It was a little slow,took about >30s) . But I canot boot in the normal system.(Loop in the lenovo logo. I don't know why) Sorry I don't have the link for 617 ota fille.

**Comment by kazegh** [comment] 2024-11-30 12:00
Hello . I have tested the TWRP. You can't apply some changes for /data.(delete /data/cache/somelog;touch /data/adb/service.d/test.sh;adb shell rm /data/system/users/0/package-restrictions.xml. These changes will restore original state after reboot)

**Comment by polygraphene** [comment] 2024-11-30 12:29
> Thank you very much. I re-flashed the boot. It worked. The tablet booted in the TWRP.(It was a little slow,took about >30s) . But 

Slow boot is normal if you have many app or files in /data. TWRP seems to check /data files at boot.

> I canot boot in the normal system.(Loop in the lenovo logo. I don't know why) Sorry I don't have the link for 617 ota fille.

I have no idea about boot loop. You re-flashed correct boot (like from .617)?

**Comment by kazegh** [comment] 2024-11-30 12:39
The question is that you can't apply any changes for partition /data! (I can't boot into system because some system apps were disabled)

**Comment by polygraphene** [comment] 2024-11-30 12:40
You decrypted /data?

**Comment by kazegh** [comment] 2024-11-30 12:49
> You decrypted /data?

 I can list and read all the files in /data by TWRP. And input the right unlock Pattern when get into TWRP.

**Comment by polygraphene** [comment] 2024-11-30 12:59
> > You decrypted /data?
> 
> I can list and read all the files in /data by TWRP. And input the right unlock Pattern when get into TWRP.

That looks right.

Hmm.. Very weird.
No problem on my .336.

**Comment by kazegh** [comment] 2024-12-02 01:12
Hello .I found the update link from xdaforums.com.
Can you please fix the failed write partition /data bug ?

TB320FC_CN_OPEN_USER_Q00031.0_U_ZUI_16.0.617_ST_241122
https://ota-cdn.lenovo.com/firmware/20241122182845316-4509.zip

**Comment by polygraphene** [comment] 2024-12-02 05:16
Thank you! I will try it.

**Comment by polygraphene** [comment] 2024-12-02 06:32
I had no problem on writing /data.
I created a file on /data/cache via adb shell, then rebooted. The file are retained after reboot without problem.
Tried another directories like `/data/data/(some application)`, and worked flawlessly.

**Comment by kazegh** [comment] 2024-12-18 02:38
> I had no problem on writing /data. I created a file on /data/cache via adb shell, then rebooted. The file are retained after reboot without problem. Tried another directories like `/data/data/(some application)`, and worked flawlessly.

Hello.
I flashed the new TWRP b0005 version(The splash screen shows b0004) It was the same that I **can't apply any changes** for partition /data(File is recovery fater reboot).

**Comment by polygraphene** [comment] 2024-12-20 18:09
Wrong build version was my mistake. Thank you for reporting. I will fix the build later.

I couldn't reproduce the issue even on cn .617 and have no idea about the issue.
How did you apply that changes? Tell me the command you typed.
Am I understanding correctly that the changes are properly applied before a restart, but go back to the original state after restarting?
The modification date of files (like, can be shown by `ls -l`) are also reverted?

**Comment by polygraphene** [comment] 2024-12-20 19:19
I have rebuilt b0005. Wrong build number are now fixed.

**Comment by kazegh** [comment] 2024-12-21 01:49
> Hello . I have tested the TWRP. You can't apply some changes for /data.(delete /data/cache/somelog;touch /data/adb/service.d/test.sh;adb shell rm /data/system/users/0/package-restrictions.xml. These changes will restore original state after reboot)

Yes. I have tried all methods to change file for /data.(File Manager direct delete /data/cache/somelog;open terminal command :touch /data/adb/service.d/test.sh;&& rm /data/system/users/0/package-restrictions.xml. These changes will applied in File Manager(shell: ls =also shows the change) ,but reverted original state after reboot)

**Closed as completed** 2024-12-30 07:59 UTC
